### ISSUE TITLE
Timestamps are not in Epoch

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.analytics#34] opened 2017-03-28 00:04 UTC
ra.session records timestamps in number of (nano)seconds since the first timestamp of the session. Since split module, radical stack records timestamps into (nano)seconds since epoch. The following use case seems to suggest we should record timestamps in (nano)seconds in RA too:

"We run n concurrent sessions on the same machine for a months in a row. We want to plot sessions at one day interval to investigate duration patterns that could depend either on RCT or on the machine"

An approach to this use case would be to find the min of all the timestamps and convert it to Epoch. Unfortunately, the min of all timestamps in the current RA implementation is 0.0.

**Comment by marksantcroos** [comment] 2017-03-28 06:21
I have little preference for the base of RA timestamps, as long as I can convert them. It sounds like currently the delta with the epoch is not recorded/exposed at all?

**Comment by mturilli** [comment] 2017-03-28 11:44
That would work for me too. I did not find it but I might have miss it :)

**Comment by ibethune** [comment] 2017-03-31 11:01
Caused by split_module, so needs to be resolved within this release.

**Closed** 2020-06-24 13:56 UTC
Labels: type:feature
