### ISSUE TITLE
argument set to create a new session is different for pilot and entk

### ISSUE THREAD

**Issue by aydinsaribudak** [radical-cybertools/radical.analytics#120] opened 2020-03-05 18:26 UTC
Hi,
The argument set used to create a new session is different for radical.pilot and radical.entk. For example;
```
    loc = './re.session.js-17-94.jetstream-cloud.org.aydins.018326.0004'
    src = os.path.dirname(loc)
    sid = os.path.basename(loc)
    re_session = ra.Session(src=src, sid = sid, stype='radical.entk')
    rp_session = ra.Session(src=src+'/'+sid, stype='radical.pilot')
```
It may be more convenient to make it unique. An improvement to use the same argument structure for both pilot and entk will help.
Thanks,
Aydin

**Comment by andre-merzky** [comment] 2020-03-05 19:11
Hmm, I am afraid I can't reproduce this.  Can you please attach your `./re.session.js-17-94.jetstream-cloud.org.aydins.018326.0004` directory as a tarball?  Thanks!

**Comment by aydinsaribudak** [comment] 2020-03-06 03:42
Hi Andre,
Session folder is attached.

To clarify the problem:
When stype is set as radical.entk, we need to provide two arguments for src and sid separately. 
`re_session = ra.Session(src=src, sid = sid, stype='radical.entk')`

When stype is set as radical.pilot, we need to provide only one argument for both src and sid. 
`rp_session = ra.Session(src=src+'/'+sid, stype='radical.pilot')`

It may be more convenient if both entk and pilot requires the same arguments when an analytics session is created.

Thanks,
Aydin

[session.tar.gz](https://github.com/radical-cybertools/radical.analytics/files/4296322/session.tar.gz)

**Comment by andre-merzky** [comment] 2020-03-06 07:47
Thanks for the session.  It appears that the profile reading in EnTK is implemented differently than in RP and RU.  This is fixed now in the EnTK branch `fix/issue_ra_120`.

**Closed** 2020-06-23 14:01 UTC
Labels: priority:high, topic:api, topic:data, type:question
